on:
  release:
    types: ['published']
  workflow_dispatch:

name: deploy

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, 2c2g4m]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.4.0
        with:
          token: ${{ secrets.ROBOT_TOKEN }}
      - name: Checkout latest release tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        id: tag
      - name: Clear existing files
        run: |
          cd /usr/share/nginx/sites/hookdown
          sudo rm -rf *
      - name: Download deployment pack
        run: |
          cd /usr/share/nginx/sites/hookdown
          sudo wget https://github.com/AkiraVoid-Productions/Hookdown/releases/download/${{ steps.tag.outputs.tag }}/hookdown-deployment-pack.zip
          sudo unzip hookdown-deployment-pack.zip
          sudo rm -f hookdown-deployment-pack.zip
      - name: Configure yarn
        run: |
          cd /usr/share/nginx/sites/hookdown
          sudo yarn config set httpProxy="http://127.0.0.1:7890"
          sudo yarn config set httpsProxy="http://127.0.0.1:7890"
          sudo yarn plugin import workspace-tools
          sudo yarn workspaces focus --production
      - name: Restart service
        run: pm2 restart ecosystem.config.js
