on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release

env:
  GH_TOKEN: ${{ secrets.ROBOT_TOKEN }}
  GIT_AUTHOR_NAME: akiravoid-bot
  GIT_AUTHOR_EMAIL: coding@akiravoid.com
  GIT_COMMITTER_NAME: akiravoid-bot
  GIT_COMMITTER_EMAIL: akiravoid-bot

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.4.0
      - name: Set node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18.15.0
      - name: Enable yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate
      - name: Install dependencies
        run: yarn install
      - name: Build package
        run: yarn build
      - name: Release
        run: yarn semantic-release
